/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__pyCalc
#define __PYX_HAVE__pyCalc


#ifndef __PYX_HAVE_API__pyCalc

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(void) cPrint(std::string);
__PYX_EXTERN_C DL_IMPORT(void) cPrint2(std::string);

#endif /* !__PYX_HAVE_API__pyCalc */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpyCalc(void);
#else
PyMODINIT_FUNC PyInit_pyCalc(void);
#endif

#endif /* !__PYX_HAVE__pyCalc */
